type GlossaryCopy = {
  term: string;
  definition: string;
  plain: string;
  why: string;
  example: string;
  relatedLabel: string;
  relatedHref: string;
};

export type GlossaryTerm = { slug: string; ru: GlossaryCopy; en: GlossaryCopy };

type SourceTerm = {
  slug: string;
  ruTerm: string;
  enTerm: string;
  ruDefinition: string;
  enDefinition: string;
  ruPlain?: string;
  enPlain?: string;
  ruWhy?: string;
  enWhy?: string;
  ruExample: string;
  enExample: string;
  relatedHref: string;
};

const sources: SourceTerm[] = [
  { slug: "seo-audit", ruTerm: "SEO-аудит", enTerm: "SEO audit", ruDefinition: "Проверка сайта, которая связывает проблему с URL, приоритетом и способом повторной проверки.", enDefinition: "A website review that connects an issue to a URL, priority and a repeatable acceptance check.", ruExample: "Например: закрытая от поиска страница и точное правило, как проверить исправление.", enExample: "For example: a blocked page plus a precise way to verify the fix.", relatedHref: "/seo-audit" },
  { slug: "indexing", ruTerm: "Индексация", enTerm: "Indexing", ruDefinition: "Добавление страницы в поисковую базу.", enDefinition: "Adding a page to a search engine index.", ruExample: "Страница открывается в браузере, но ещё не появилась в поиске.", enExample: "A page opens in a browser but is not yet present in search.", relatedHref: "/seo-audit" },
  { slug: "crawling", ruTerm: "Сканирование", enTerm: "Crawling", ruDefinition: "Автоматический обход ссылок и страниц роботом.", enDefinition: "Automated discovery of links and pages by a crawler.", ruExample: "Робот переходит с главной страницы в каталог по внутренним ссылкам.", enExample: "A crawler follows internal links from the home page into a catalogue.", relatedHref: "/seo-audit" },
  {
    slug: "search-crawler",
    ruTerm: "Поисковый робот",
    enTerm: "Search crawler",
    ruDefinition: "Программа поисковой системы, которая открывает доступные URL и передаёт найденные данные на обработку.",
    enDefinition: "A search-engine program that opens accessible URLs and sends discovered data for processing.",
    ruPlain: "Это автоматический посетитель: он переходит по ссылкам и смотрит, какие страницы сайт разрешает прочитать.",
    enPlain: "It is an automated visitor that follows links and checks which pages the website allows it to read.",
    ruWhy: "Если робот не может открыть важную страницу, она не попадёт в поиск независимо от качества текста.",
    enWhy: "If the crawler cannot open an important page, that page cannot enter search regardless of copy quality.",
    ruExample: "Робот находит новую услугу по ссылке из меню и добавляет URL в очередь обхода.",
    enExample: "The crawler finds a new service through the menu and adds its URL to the crawl queue.",
    relatedHref: "/seo-audit",
  },
  { slug: "robots-txt", ruTerm: "robots.txt", enTerm: "robots.txt", ruDefinition: "Файл с правилами обхода для поисковых роботов.", enDefinition: "A file containing crawling rules for search robots.", ruExample: "Правило может закрыть служебный раздел от обхода.", enExample: "A rule can prevent a utility section from being crawled.", relatedHref: "/seo-audit" },
  { slug: "sitemap", ruTerm: "sitemap", enTerm: "Sitemap", ruDefinition: "Список выбранных URL, который помогает поиску обнаруживать страницы.", enDefinition: "A selected URL list that helps search engines discover pages.", ruExample: "В карту включают канонические страницы услуг и статей.", enExample: "The map contains canonical service and article pages.", relatedHref: "/seo-audit" },
  { slug: "canonical", ruTerm: "Canonical", enTerm: "Canonical", ruDefinition: "Сигнал о предпочтительной версии среди похожих URL.", enDefinition: "A signal indicating the preferred version among similar URLs.", ruExample: "Фильтр каталога указывает основной адрес категории.", enExample: "A catalogue filter points to the main category URL.", relatedHref: "/seo-audit" },
  { slug: "redirect", ruTerm: "Редирект", enTerm: "Redirect", ruDefinition: "Перенаправление с одного адреса на другой.", enDefinition: "An instruction sending visitors and crawlers from one URL to another.", ruExample: "Старый адрес услуги ведёт на новый постоянным редиректом.", enExample: "An old service URL permanently redirects to the new one.", relatedHref: "/web-development" },
  { slug: "http-404", ruTerm: "Ошибка 404", enTerm: "404 response", ruDefinition: "Ответ сервера о том, что ресурс не найден.", enDefinition: "A server response stating that a resource was not found.", ruExample: "Удалённый товар возвращает 404, а не пустую страницу с кодом 200.", enExample: "A removed product returns 404 rather than an empty 200 page.", relatedHref: "/seo-audit" },
  { slug: "title", ruTerm: "Title", enTerm: "Title", ruDefinition: "Название HTML-документа для вкладки и поисковой выдачи.", enDefinition: "The HTML document title used in tabs and often in search results.", ruExample: "У каждой услуги свой конкретный title.", enExample: "Each service has its own specific title.", relatedHref: "/content-materials" },
  { slug: "description", ruTerm: "Description", enTerm: "Description", ruDefinition: "Краткое описание страницы для поисковых систем.", enDefinition: "A concise page description for search engines.", ruExample: "Описание объясняет услугу и не повторяет заголовок дословно.", enExample: "The description explains the service without copying the heading.", relatedHref: "/content-materials" },
  { slug: "heading-h1", ruTerm: "H1", enTerm: "H1", ruDefinition: "Основной видимый заголовок страницы.", enDefinition: "The main visible heading of a page.", ruExample: "H1 отвечает, что предлагает конкретная страница.", enExample: "The H1 states what the page offers.", relatedHref: "/content-materials" },
  {
    slug: "meta-tags",
    ruTerm: "Метатеги",
    enTerm: "Meta tags",
    ruDefinition: "Элементы HTML, которые передают поисковым системам служебные сведения о странице.",
    enDefinition: "HTML elements that provide search engines with supporting information about a page.",
    ruPlain: "Это подписи в коде страницы: посетитель обычно их не видит, но поиск использует их для понимания и показа результата.",
    enPlain: "They are labels in the page code: visitors usually do not see them, but search engines use them to understand and present the result.",
    ruWhy: "Некорректные или одинаковые метатеги мешают отличить страницы и сформировать понятный сниппет.",
    enWhy: "Incorrect or duplicated meta tags make pages harder to distinguish and can weaken the search snippet.",
    ruExample: "Title называет услугу, а description коротко объясняет предложение без повторения заголовка.",
    enExample: "The title names the service and the description explains the offer without repeating the heading.",
    relatedHref: "/content-materials",
  },
  { slug: "on-page", ruTerm: "On-page", enTerm: "On-page", ruDefinition: "Содержание и разметка самой страницы.", enDefinition: "The content and markup of the page itself.", ruExample: "Заголовки, текст, ссылки, изображения и структурированные данные.", enExample: "Headings, copy, links, images and structured data.", relatedHref: "/seo-promotion" },
  { slug: "internal-link", ruTerm: "Внутренняя ссылка", enTerm: "Internal link", ruDefinition: "Ссылка между страницами одного сайта.", enDefinition: "A link between pages on the same website.", ruExample: "Статья ведёт на подходящую услугу, а услуга — на кейс.", enExample: "An article links to a relevant service, and the service links to a case.", relatedHref: "/seo-promotion" },
  {
    slug: "internal-linking",
    ruTerm: "Перелинковка",
    enTerm: "Internal linking",
    ruDefinition: "Система внутренних ссылок, которая соединяет связанные страницы сайта.",
    enDefinition: "A system of internal links connecting related pages across a website.",
    ruPlain: "Страницы не остаются изолированными: читатель и поисковый робот могут перейти к логичному продолжению.",
    enPlain: "Pages are not left isolated: readers and crawlers can move to the logical next page.",
    ruWhy: "Перелинковка помогает обнаруживать страницы, передаёт контекст и ведёт посетителя к следующему действию.",
    enWhy: "Internal linking helps discovery, supplies context and guides visitors towards the next action.",
    ruExample: "Статья о бесплатной проверке ведёт на услугу аудита, а страница услуги — на подтверждающий кейс.",
    enExample: "An article about a free check links to the audit service, and the service links to an evidence-based case.",
    relatedHref: "/seo-promotion",
  },
  { slug: "duplicate-page", ruTerm: "Дубль страницы", enTerm: "Duplicate page", ruDefinition: "URL с тем же или почти тем же содержанием, что другая страница.", enDefinition: "A URL with the same or nearly the same content as another page.", ruExample: "Один товар доступен по нескольким параметризованным адресам.", enExample: "One product is available through several parameterised URLs.", relatedHref: "/seo-audit" },
  { slug: "schema-org", ruTerm: "Schema.org", enTerm: "Schema.org", ruDefinition: "Словарь структурированных данных для описания сущностей страницы.", enDefinition: "A structured-data vocabulary used to describe page entities.", ruExample: "Страница размечает организацию, статью или товар.", enExample: "A page describes an organisation, article or product.", relatedHref: "/web-development" },
  {
    slug: "structured-data",
    ruTerm: "Структурированные данные",
    enTerm: "Structured data",
    ruDefinition: "Машиночитаемая разметка, которая явно описывает сущности и свойства страницы.",
    enDefinition: "Machine-readable markup that explicitly describes page entities and their properties.",
    ruPlain: "Это понятная поисковой системе карточка фактов: что перед ней — статья, товар, организация или другой объект.",
    enPlain: "It is a fact card for search engines that states whether the page represents an article, product, organisation or another entity.",
    ruWhy: "Корректная разметка уменьшает неоднозначность и даёт поиску данные для расширенного представления результата.",
    enWhy: "Correct markup reduces ambiguity and gives search engines data for richer result presentation.",
    ruExample: "Карточка товара передаёт название, цену, наличие и бренд через Product-разметку.",
    enExample: "A product page supplies its name, price, availability and brand through Product markup.",
    relatedHref: "/web-development",
  },
  { slug: "json-ld", ruTerm: "JSON-LD", enTerm: "JSON-LD", ruDefinition: "Формат добавления структурированных данных отдельным блоком.", enDefinition: "A format for adding structured data in a separate block.", ruExample: "Данные о статье передаются в script-блоке.", enExample: "Article data is supplied in a script block.", relatedHref: "/web-development" },
  { slug: "core-web-vitals", ruTerm: "Core Web Vitals", enTerm: "Core Web Vitals", ruDefinition: "Полевые показатели загрузки, отзывчивости и стабильности страницы.", enDefinition: "Field metrics for loading, responsiveness and visual stability.", ruExample: "Проверяются LCP, INP и CLS по реальным посещениям.", enExample: "LCP, INP and CLS are measured from real visits.", relatedHref: "/seo-audit" },
  { slug: "lcp", ruTerm: "LCP", enTerm: "LCP", ruDefinition: "Время появления крупнейшего заметного элемента.", enDefinition: "The time when the largest visible content element appears.", ruExample: "Крупный баннер не должен задерживать показ основного смысла.", enExample: "A large banner should not delay the page's main message.", relatedHref: "/web-development" },
  { slug: "cls", ruTerm: "CLS", enTerm: "CLS", ruDefinition: "Показатель неожиданных сдвигов уже показанных элементов.", enDefinition: "A measure of unexpected shifts of already visible elements.", ruExample: "Кнопка не уезжает вниз после загрузки изображения.", enExample: "A button does not jump down after an image loads.", relatedHref: "/web-development" },
  {
    slug: "tbt",
    ruTerm: "TBT",
    enTerm: "TBT",
    ruDefinition: "Лабораторный показатель времени, когда главный поток заблокирован длинными задачами.",
    enDefinition: "A lab metric measuring how long the main thread is blocked by long tasks.",
    ruPlain: "Показывает, сколько времени страница занята тяжёлой работой и не может быстро ответить на действие пользователя.",
    enPlain: "It shows how long the page is busy with heavy work and cannot respond promptly to user input.",
    ruWhy: "Высокий TBT помогает найти JavaScript и другие задачи, из-за которых интерфейс ощущается зависшим.",
    enWhy: "A high TBT helps identify JavaScript and other work that makes the interface feel frozen.",
    ruExample: "Большой скрипт блокирует нажатие на меню на 600 мс после загрузки.",
    enExample: "A large script blocks the menu interaction for 600 ms after loading.",
    relatedHref: "/web-development",
  },
  { slug: "inp", ruTerm: "INP", enTerm: "INP", ruDefinition: "Полевой показатель задержки интерфейса после действия пользователя.", enDefinition: "A field metric for interface response latency after interaction.", ruExample: "Меню быстро реагирует на нажатие даже на слабом телефоне.", enExample: "A menu responds quickly even on a slower phone.", relatedHref: "/web-development" },
  { slug: "ctr", ruTerm: "CTR", enTerm: "CTR", ruDefinition: "Доля кликов от числа показов.", enDefinition: "Clicks divided by impressions.", ruExample: "У объявления 1000 показов и 40 кликов: CTR равен 4%.", enExample: "An ad has 1,000 impressions and 40 clicks: its CTR is 4%.", relatedHref: "/yandex-ads" },
  {
    slug: "conversion",
    ruTerm: "Конверсия",
    enTerm: "Conversion",
    ruDefinition: "Целевое действие пользователя и доля посетителей, которые его совершили.",
    enDefinition: "A target user action and the share of visitors who complete it.",
    ruPlain: "Это нужный бизнесу результат визита: заявка, звонок, покупка или другое заранее выбранное действие.",
    enPlain: "It is the visit outcome the business needs, such as an enquiry, call, purchase or another agreed action.",
    ruWhy: "Без конкретной конверсии нельзя связать изменения сайта или рекламы с измеримым результатом.",
    enWhy: "Without a defined conversion, website or advertising changes cannot be tied to a measurable outcome.",
    ruExample: "Из 200 посетителей форму отправили 8: конверсия формы составила 4%.",
    enExample: "Eight of 200 visitors submit the form, giving the form a 4% conversion rate.",
    relatedHref: "/yandex-ads",
  },
  { slug: "search-semantics", ruTerm: "Семантика", enTerm: "Search semantics", ruDefinition: "Набор поисковых запросов и намерений пользователей.", enDefinition: "A set of search queries and user intents.", ruExample: "Запросы о цене и инструкции относятся к разным задачам.", enExample: "Price queries and how-to queries represent different tasks.", relatedHref: "/seo-promotion" },
  { slug: "query-cluster", ruTerm: "Кластер запросов", enTerm: "Query cluster", ruDefinition: "Группа запросов с близким намерением.", enDefinition: "A group of queries with a shared intent.", ruExample: "Близкие запросы обслуживает одна сильная посадочная страница.", enExample: "Related queries are served by one strong landing page.", relatedHref: "/seo-promotion" },
  {
    slug: "semantic-core",
    ruTerm: "Семантическое ядро",
    enTerm: "Keyword set",
    ruDefinition: "Проверенный набор поисковых запросов, сгруппированных по темам и намерениям.",
    enDefinition: "A validated set of search queries grouped by topic and intent.",
    ruPlain: "Это карта того, как люди формулируют свои задачи в поиске и каким страницам отвечать на каждую формулировку.",
    enPlain: "It is a map of how people phrase their needs in search and which page should answer each query group.",
    ruWhy: "Ядро помогает планировать структуру без случайных страниц и бессмысленного повторения фраз.",
    enWhy: "The set helps plan a deliberate structure without random pages or mechanical phrase repetition.",
    ruExample: "Запросы про цену аудита относятся к коммерческой странице, а запросы про состав аудита — к объясняющему материалу.",
    enExample: "Audit-price queries belong on a commercial page, while audit-scope queries can be answered by an explanatory article.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "query-clustering",
    ruTerm: "Кластеризация",
    enTerm: "Query clustering",
    ruDefinition: "Объединение поисковых запросов в группы, которые может полноценно закрыть одна страница.",
    enDefinition: "Grouping search queries that can be answered well by a single page.",
    ruPlain: "Похожие по задаче формулировки собирают вместе, а разные намерения разводят по отдельным страницам.",
    enPlain: "Phrases with the same job are kept together, while different intents are assigned to different pages.",
    ruWhy: "Кластеризация предотвращает лишние страницы и помогает не смешивать разные пользовательские задачи.",
    enWhy: "Clustering prevents unnecessary pages and avoids mixing different user needs on one page.",
    ruExample: "Запросы «заказать SEO-аудит» и «стоимость SEO-аудита» могут вести на одну страницу услуги.",
    enExample: "Queries such as “order an SEO audit” and “SEO audit cost” can lead to one service page.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "search-intent",
    ruTerm: "Поисковый интент",
    enTerm: "Search intent",
    ruDefinition: "Задача, которую пользователь хочет решить своим поисковым запросом.",
    enDefinition: "The task a user wants to complete with a search query.",
    ruPlain: "Важно не только какие слова введены, но и нужен ли человеку ответ, сравнение, адрес или покупка.",
    enPlain: "The words alone are not enough: the user may need an answer, comparison, location or purchase.",
    ruWhy: "Страница, не соответствующая намерению, редко помогает посетителю даже при точном совпадении ключевой фразы.",
    enWhy: "A page that misses the intent rarely helps the visitor even when it contains the exact query wording.",
    ruExample: "По запросу «что входит в SEO-аудит» человеку нужен состав работ, а не форма заказа без объяснения.",
    enExample: "For “what does an SEO audit include”, the user needs a scope explanation rather than an unexplained order form.",
    relatedHref: "/content-materials",
  },
  {
    slug: "page-cannibalisation",
    ruTerm: "Каннибализация страниц",
    enTerm: "Page cannibalisation",
    ruDefinition: "Ситуация, когда несколько страниц одного сайта конкурируют за одну поисковую задачу.",
    enDefinition: "A situation where several pages on one website compete for the same search task.",
    ruPlain: "Поиску трудно выбрать главный ответ, потому что сайт предлагает несколько почти одинаковых страниц.",
    enPlain: "Search engines struggle to choose the primary answer because the website offers several nearly identical pages.",
    ruWhy: "Конкурирующие страницы могут менять позиции друг друга и размывать накопленные сигналы.",
    enWhy: "Competing pages can displace one another and split the signals each page has accumulated.",
    ruExample: "Две страницы «SEO-аудит сайта» различаются только переставленными абзацами и претендуют на один запрос.",
    enExample: "Two “website SEO audit” pages differ only by reordered paragraphs and target the same query.",
    relatedHref: "/seo-audit",
  },
  { slug: "landing-page", ruTerm: "Посадочная страница", enTerm: "Landing page", ruDefinition: "Страница для конкретной задачи или предложения.", enDefinition: "A page designed for a specific task or offer.", ruExample: "Отдельная страница объясняет аудит и ведёт к брифу.", enExample: "A dedicated page explains the audit and leads to the brief.", relatedHref: "/web-development" },
  { slug: "product-feed", ruTerm: "Товарный фид", enTerm: "Product feed", ruDefinition: "Структурированный файл с товарами и параметрами.", enDefinition: "A structured file containing products and attributes.", ruExample: "Фид передаёт Маркету цены, остатки и характеристики.", enExample: "A feed supplies Market with prices, stock and attributes.", relatedHref: "/marketplaces/yandex-market" },
  { slug: "product-attribute", ruTerm: "Атрибут товара", enTerm: "Product attribute", ruDefinition: "Характеристика товара для фильтров, сравнения и карточки.", enDefinition: "A product characteristic used in filters, comparisons and cards.", ruExample: "Материал, размер, цвет или мощность.", enExample: "Material, size, colour or power.", relatedHref: "/marketplaces" },
  {
    slug: "sku",
    ruTerm: "SKU",
    enTerm: "SKU",
    ruDefinition: "Уникальная товарная позиция, обычно отличающаяся конкретным набором характеристик.",
    enDefinition: "A unique stock-keeping unit, usually defined by a specific combination of product attributes.",
    ruPlain: "Это отдельный вариант товара, который магазин учитывает и продаёт как самостоятельную позицию.",
    enPlain: "It is a distinct product variant that the seller tracks and sells as its own item.",
    ruWhy: "Корректное разделение SKU влияет на остатки, цены, варианты и качество данных в карточке.",
    enWhy: "Correct SKU separation affects stock, pricing, variants and product-card data quality.",
    ruExample: "Одна модель футболки в размерах S и M — два разных SKU.",
    enExample: "The same T-shirt model in sizes S and M represents two separate SKUs.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "product-card",
    ruTerm: "Карточка товара",
    enTerm: "Product card",
    ruDefinition: "Страница товара с названием, характеристиками, изображениями, ценой и условиями покупки.",
    enDefinition: "A product page containing the name, attributes, images, price and purchase conditions.",
    ruPlain: "Это основная страница, на которой покупатель понимает товар и принимает решение о покупке.",
    enPlain: "It is the main page where a shopper understands the product and decides whether to buy it.",
    ruWhy: "Полнота и согласованность карточки влияют на поиск по каталогу, доверие и конверсию.",
    enWhy: "A complete, consistent product card affects catalogue discovery, trust and conversion.",
    ruExample: "Карточка обуви показывает модель, размерную сетку, материал, фото, цену и наличие.",
    enExample: "A footwear card shows the model, size guide, material, images, price and availability.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "rich-content",
    ruTerm: "Rich Content",
    enTerm: "Rich Content",
    ruDefinition: "Расширенный визуальный контент карточки товара: дополнительные блоки, изображения и объяснения.",
    enDefinition: "Enhanced visual content for a product card, including extra blocks, images and explanations.",
    ruPlain: "Это подробная презентация товара ниже основных характеристик, если площадка поддерживает такой формат.",
    enPlain: "It is a more detailed product presentation below the core attributes when the marketplace supports the format.",
    ruWhy: "Rich Content может наглядно объяснить сложный товар, но не заменяет точные основные характеристики.",
    enWhy: "Rich Content can explain a complex product visually, but it does not replace accurate core attributes.",
    ruExample: "Для кофемашины добавляют схему режимов, размеры и последовательность ухода.",
    enExample: "A coffee-machine card adds a mode diagram, dimensions and a maintenance sequence.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "ab-testing",
    ruTerm: "A/B-тестирование",
    enTerm: "A/B testing",
    ruDefinition: "Сравнение двух вариантов при контролируемом распределении аудитории.",
    enDefinition: "A comparison of two variants using a controlled audience split.",
    ruPlain: "Часть людей видит вариант A, часть — вариант B, после чего результат сравнивают по заранее выбранной метрике.",
    enPlain: "Some users see variant A and others see variant B, then results are compared using a metric chosen in advance.",
    ruWhy: "Тест помогает отличить реальный эффект изменения от случайных колебаний и субъективного мнения.",
    enWhy: "The test helps separate a real effect from random variation and subjective preference.",
    ruExample: "Сравнивают две формулировки кнопки по доле отправленных форм при одинаковых условиях.",
    enExample: "Two button labels are compared by form-completion rate under the same conditions.",
    relatedHref: "/content-materials",
  },
  { slug: "acceptance-criterion", ruTerm: "Критерий приёмки", enTerm: "Acceptance criterion", ruDefinition: "Заранее согласованное проверяемое условие завершения работы.", enDefinition: "A pre-agreed testable condition used to accept completed work.", ruExample: "После правки все выбранные URL возвращают ожидаемый код ответа.", enExample: "After the fix, every selected URL returns the expected status.", relatedHref: "/brief" },
];

export const glossaryTerms: GlossaryTerm[] = sources.map((source) => ({
  slug: source.slug,
  ru: {
    term: source.ruTerm,
    definition: source.ruDefinition,
    plain: source.ruPlain ?? `Проще: ${source.ruDefinition.charAt(0).toLowerCase()}${source.ruDefinition.slice(1)}`,
    why: source.ruWhy ?? "Термин помогает точно описать проблему, договориться о результате и проверить работу.",
    example: source.ruExample,
    relatedLabel: "Связанный раздел",
    relatedHref: source.relatedHref,
  },
  en: {
    term: source.enTerm,
    definition: source.enDefinition,
    plain: source.enPlain ?? `In plain language: ${source.enDefinition.charAt(0).toLowerCase()}${source.enDefinition.slice(1)}`,
    why: source.enWhy ?? "The term helps define the issue, agree the outcome and verify delivery.",
    example: source.enExample,
    relatedLabel: "Related page",
    relatedHref: `/en${source.relatedHref}`,
  },
}));
