type GlossaryCopy = {
  term: string;
  definition: string;
  plain: string;
  why: string;
  example: string;
  relatedLabel: string;
  relatedHref: string;
};

export type GlossaryTerm = {
  slug: string;
  /** Publish a dedicated URL only after both locales have term-specific copy. */
  indexable: boolean;
  /** Content date used by sitemap integrations; update only after a real editorial change. */
  updatedAt: string;
  ru: GlossaryCopy;
  en: GlossaryCopy;
};

type SourceTerm = {
  slug: string;
  indexable?: boolean;
  updatedAt?: string;
  ruTerm: string;
  enTerm: string;
  ruDefinition: string;
  enDefinition: string;
  ruPlain?: string;
  enPlain?: string;
  ruWhy?: string;
  enWhy?: string;
  ruExample: string;
  enExample: string;
  relatedHref: string;
};

const sources: SourceTerm[] = [
  {
    slug: "seo-audit",
    indexable: true,
    updatedAt: "2026-08-28",
    ruTerm: "SEO-аудит",
    enTerm: "SEO audit",
    ruDefinition: "Системная проверка сайта, которая связывает каждую поисковую проблему с URL, приоритетом, причиной и способом повторной проверки.",
    enDefinition: "A systematic website review that connects every search issue to a URL, priority, cause and repeatable verification method.",
    ruPlain: "Аудит показывает не просто список ошибок, а где именно теряется доступность, понятность или ценность страницы и что нужно проверить после исправления.",
    enPlain: "An audit shows not only a list of errors, but exactly where a page loses accessibility, clarity or value and what must be checked after the fix.",
    ruWhy: "Он отделяет критичные препятствия для обхода и индексации от рекомендаций низкого риска, поэтому команда исправляет причины по приоритету, а не меняет сайт наугад.",
    enWhy: "It separates critical crawling and indexing barriers from low-risk recommendations, so the team fixes root causes in priority order instead of changing the site at random.",
    ruExample: "Обход находит noindex на коммерческой странице, аудит фиксирует затронутый URL и источник директивы, после правки повторная проверка подтверждает ответ 200 и разрешённую индексацию.",
    enExample: "A crawl finds noindex on a commercial page; the audit records the affected URL and directive source, then a repeat check confirms a 200 response and permitted indexing.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "indexing",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Индексация",
    enTerm: "Indexing",
    ruDefinition: "Добавление обработанной страницы в поисковую базу, из которой формируются результаты поиска.",
    enDefinition: "Adding a processed page to the search-engine database used to build search results.",
    ruPlain: "После обхода поиск анализирует страницу и решает, сохранять ли её как отдельный ответ на запросы пользователей.",
    enPlain: "After crawling, the search engine analyses the page and decides whether to store it as a distinct answer to user queries.",
    ruWhy: "Доступный URL не обязательно индексируется: мешать могут запреты, дубли, слабое содержание или выбор другой канонической версии.",
    enWhy: "An accessible URL is not necessarily indexed: directives, duplication, weak content or another canonical version may prevent inclusion.",
    ruExample: "Новая статья возвращает 200, разрешена к обходу и через время появляется в базе поиска со своим каноническим URL.",
    enExample: "A new article returns 200, allows crawling and later enters the index under its canonical URL.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "crawling",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Сканирование",
    enTerm: "Crawling",
    ruDefinition: "Автоматический обход доступных URL и ссылок поисковым роботом.",
    enDefinition: "Automated exploration of accessible URLs and links by a search crawler.",
    ruPlain: "Робот открывает страницу, читает ответ сервера и разметку, затем переходит по найденным ссылкам к следующим URL.",
    enPlain: "The crawler opens a page, reads the server response and markup, then follows discovered links to further URLs.",
    ruWhy: "Без стабильного обхода поиск не увидит новые страницы и не узнает об изменениях на уже известных адресах.",
    enWhy: "Without reliable crawling, search engines cannot discover new pages or notice changes on URLs they already know.",
    ruExample: "Ссылка из раздела блога приводит робота к новой статье, после чего её содержимое отправляется на обработку.",
    enExample: "A link from the blog hub leads the crawler to a new article, whose content is then sent for processing.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "search-crawler",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Поисковый робот",
    enTerm: "Search crawler",
    ruDefinition: "Программа поисковой системы, которая открывает доступные URL и передаёт найденные данные на обработку.",
    enDefinition: "A search-engine program that opens accessible URLs and sends discovered data for processing.",
    ruPlain: "Это автоматический посетитель: он переходит по ссылкам и смотрит, какие страницы сайт разрешает прочитать.",
    enPlain: "It is an automated visitor that follows links and checks which pages the website allows it to read.",
    ruWhy: "Если робот не может открыть важную страницу, она не попадёт в поиск независимо от качества текста.",
    enWhy: "If the crawler cannot open an important page, that page cannot enter search regardless of copy quality.",
    ruExample: "Робот находит новую услугу по ссылке из меню и добавляет URL в очередь обхода.",
    enExample: "The crawler finds a new service through the menu and adds its URL to the crawl queue.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "robots-txt",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "robots.txt",
    enTerm: "robots.txt",
    ruDefinition: "Текстовый файл в корне сайта с правилами обхода отдельных путей для поисковых роботов.",
    enDefinition: "A text file at the website root containing crawl rules for selected paths and search crawlers.",
    ruPlain: "Файл сообщает роботам, какие разделы можно запрашивать, а какие служебные адреса не стоит обходить.",
    enPlain: "The file tells crawlers which sections they may request and which utility paths they should avoid.",
    ruWhy: "Ошибочное широкое правило может закрыть важный раздел, а отсутствие запрета — расходовать обход на фильтры и технические URL.",
    enWhy: "An overly broad rule can block an important section, while missing rules may waste crawl activity on filters and utility URLs.",
    ruExample: "Раздел администрирования закрывают от обхода, но CSS, изображения и публичные страницы оставляют доступными.",
    enExample: "The administration area is disallowed while CSS, images and public pages remain crawlable.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "sitemap",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "sitemap",
    enTerm: "Sitemap",
    ruDefinition: "XML-карта с выбранными каноническими URL, которые владелец сайта предлагает поиску для обнаружения.",
    enDefinition: "An XML map of selected canonical URLs that the website owner submits for search discovery.",
    ruPlain: "Это актуальный перечень страниц, которые сайт считает самостоятельными и готовыми к появлению в поиске.",
    enPlain: "It is an up-to-date list of pages the website considers distinct and ready to appear in search.",
    ruWhy: "Карта ускоряет обнаружение глубоко расположенных страниц и помогает контролировать, какие URL сайт заявляет как основные.",
    enWhy: "A sitemap supports discovery of deeper pages and makes it easier to control which URLs the website presents as primary.",
    ruExample: "В sitemap входят канонические услуги и статьи с датой реального обновления, но не результаты форм и параметризованные дубли.",
    enExample: "The sitemap includes canonical services and articles with genuine update dates, but excludes form results and parameter duplicates.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "canonical",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Canonical",
    enTerm: "Canonical",
    ruDefinition: "Сигнал в HTML о предпочтительной версии страницы среди одинаковых или очень похожих URL.",
    enDefinition: "An HTML signal identifying the preferred page among identical or very similar URLs.",
    ruPlain: "Если одно содержание открывается по нескольким адресам, canonical указывает поиску основной URL для объединения сигналов.",
    enPlain: "When the same content is available at several addresses, canonical points search engines to the primary URL for signal consolidation.",
    ruWhy: "Согласованный canonical снижает риск конкуренции дублей, но остаётся рекомендацией и должен совпадать с редиректами и ссылками.",
    enWhy: "A consistent canonical reduces duplicate competition, but remains a hint and should agree with redirects and internal links.",
    ruExample: "Версия категории с сортировкой указывает canonical на чистый адрес категории без параметров.",
    enExample: "A sorted category version points its canonical to the clean category URL without parameters.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "redirect",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Редирект",
    enTerm: "Redirect",
    ruDefinition: "HTTP-перенаправление, которое отправляет браузер и поискового робота с одного URL на другой.",
    enDefinition: "An HTTP response that sends browsers and search crawlers from one URL to another.",
    ruPlain: "Сервер сообщает, что нужный ресурс находится по другому адресу, и указывает этот адрес в ответе.",
    enPlain: "The server states that the requested resource is available elsewhere and supplies the destination address.",
    ruWhy: "Корректный постоянный редирект сохраняет путь пользователя и помогает перенести накопленные сигналы при смене URL.",
    enWhy: "A correct permanent redirect preserves the user journey and helps transfer accumulated signals when a URL changes.",
    ruExample: "После переименования услуги старый URL одним редиректом 301 ведёт на действующую страницу без цепочки переходов.",
    enExample: "After a service is renamed, its old URL uses one 301 redirect to the current page without a redirect chain.",
    relatedHref: "/web-development",
  },
  {
    slug: "http-404",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Ошибка 404",
    enTerm: "404 response",
    ruDefinition: "HTTP-ответ сервера, подтверждающий, что запрошенный ресурс по этому адресу не найден.",
    enDefinition: "An HTTP server response confirming that the requested resource was not found at that address.",
    ruPlain: "Браузер получает честный технический статус отсутствующей страницы, даже если сайт показывает оформленное сообщение и навигацию.",
    enPlain: "The browser receives an accurate missing-page status even when the website displays a designed message and navigation.",
    ruWhy: "Правильный 404 не позволяет пустым или удалённым URL выглядеть для поиска как действующие страницы с кодом 200.",
    enWhy: "A correct 404 prevents empty or removed URLs from looking like valid 200 pages to search engines.",
    ruExample: "Удалённая карточка без подходящей замены возвращает 404 и предлагает перейти в актуальную категорию.",
    enExample: "A removed product with no suitable replacement returns 404 and offers a link to the current category.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "title",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Title",
    enTerm: "Title",
    ruDefinition: "Название HTML-документа, которое видно во вкладке и часто используется как заголовок поискового результата.",
    enDefinition: "The HTML document title shown in the browser tab and often used as the search-result heading.",
    ruPlain: "Title кратко называет конкретную страницу в коде и помогает отличить её от других страниц сайта.",
    enPlain: "The title briefly names a specific page in the code and helps distinguish it from other pages on the website.",
    ruWhy: "Уникальный и точный title передаёт тему страницы, влияет на понятность сниппета и не должен превращаться в список ключевых слов.",
    enWhy: "A precise unique title communicates the page topic and improves snippet clarity without becoming a list of keywords.",
    ruExample: "Страница услуги получает title «SEO-аудит сайта: состав и цена», а не общее «Главная | Компания».",
    enExample: "A service page uses “Website SEO audit: scope and pricing” rather than the generic “Home | Company”.",
    relatedHref: "/content-materials",
  },
  {
    slug: "description",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Description",
    enTerm: "Description",
    ruDefinition: "Краткое метаописание содержания страницы, которое поисковая система может использовать в сниппете.",
    enDefinition: "A concise meta description of page content that a search engine may use in the result snippet.",
    ruPlain: "Описание в коде заранее формулирует, что человек найдёт на странице, хотя поиск может собрать другой фрагмент из текста.",
    enPlain: "The code summary states what a visitor will find, although the search engine may select a different passage from the page.",
    ruWhy: "Конкретный description помогает понять ценность результата до клика; одинаковые и пустые описания теряют эту возможность.",
    enWhy: "A specific description communicates value before the click; empty or duplicated descriptions lose that opportunity.",
    ruExample: "Описание аудита называет проверяемый объём, результат и ограничение без повторения title слово в слово.",
    enExample: "An audit description states the reviewed scope, result and limitation without repeating the title word for word.",
    relatedHref: "/content-materials",
  },
  {
    slug: "heading-h1",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "H1",
    enTerm: "H1",
    ruDefinition: "Главный видимый HTML-заголовок, который формулирует основную тему конкретной страницы.",
    enDefinition: "The main visible HTML heading that states the primary topic of a particular page.",
    ruPlain: "Это заголовок внутри самой страницы: он сразу объясняет посетителю, куда тот попал и о чём будет содержание.",
    enPlain: "It is the heading inside the page that immediately tells visitors where they are and what the content covers.",
    ruWhy: "Понятный H1 создаёт смысловой ориентир для человека и структуры документа; декоративный или отсутствующий заголовок этот ориентир ломает.",
    enWhy: "A clear H1 anchors the visitor and document structure, while a missing or purely decorative heading weakens that orientation.",
    ruExample: "На странице аудита H1 называет проверку сайта, а последующие H2 раскрывают состав, процесс и результат.",
    enExample: "On an audit page, the H1 names the website review and subsequent H2 headings explain scope, process and outcome.",
    relatedHref: "/content-materials",
  },
  {
    slug: "meta-tags",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Метатеги",
    enTerm: "Meta tags",
    ruDefinition: "Элементы HTML, которые передают поисковым системам служебные сведения о странице.",
    enDefinition: "HTML elements that provide search engines with supporting information about a page.",
    ruPlain: "Это подписи в коде страницы: посетитель обычно их не видит, но поиск использует их для понимания и показа результата.",
    enPlain: "They are labels in the page code: visitors usually do not see them, but search engines use them to understand and present the result.",
    ruWhy: "Некорректные или одинаковые метатеги мешают отличить страницы и сформировать понятный сниппет.",
    enWhy: "Incorrect or duplicated meta tags make pages harder to distinguish and can weaken the search snippet.",
    ruExample: "Title называет услугу, а description коротко объясняет предложение без повторения заголовка.",
    enExample: "The title names the service and the description explains the offer without repeating the heading.",
    relatedHref: "/content-materials",
  },
  {
    slug: "on-page",
    indexable: true,
    updatedAt: "2026-08-28",
    ruTerm: "On-page",
    enTerm: "On-page",
    ruDefinition: "Содержание, HTML-разметка и внутренние поисковые сигналы, которыми можно управлять на конкретной странице сайта.",
    enDefinition: "The content, HTML markup and internal search signals that can be controlled on a specific website page.",
    ruPlain: "Это всё, что помогает человеку и поисковому роботу понять один URL: title, H1, основной текст, ссылки, изображения, canonical и структурированные данные.",
    enPlain: "It covers everything that helps a visitor and crawler understand one URL: title, H1, main copy, links, images, canonical and structured data.",
    ruWhy: "Согласованные on-page элементы делают назначение страницы однозначным, помогают отвечать на нужное намерение и не дают близким URL конкурировать друг с другом.",
    enWhy: "Consistent on-page elements make the page purpose clear, match the intended need and reduce competition between closely related URLs.",
    ruExample: "Страница услуги получает уникальные title и H1, ответ на вопрос о результате, ссылки на кейсы и canonical на собственный чистый URL.",
    enExample: "A service page receives a unique title and H1, a clear outcome explanation, links to evidence and a canonical pointing to its own clean URL.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "internal-link",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Внутренняя ссылка",
    enTerm: "Internal link",
    ruDefinition: "Ссылка с одной страницы сайта на другую страницу того же домена.",
    enDefinition: "A link from one website page to another page on the same domain.",
    ruPlain: "Она соединяет связанные материалы внутри сайта и даёт человеку или роботу понятный путь к следующей странице.",
    enPlain: "It connects related material within the website and gives visitors or crawlers a clear route to the next page.",
    ruWhy: "Текст ссылки и место перехода передают контекст, помогают обнаружению URL и уменьшают число изолированных страниц.",
    enWhy: "The anchor text and destination provide context, support URL discovery and reduce the number of isolated pages.",
    ruExample: "Статья о метатегах с понятного текста ссылки ведёт на страницу SEO-аудита, где можно проверить их на сайте.",
    enExample: "An article about meta tags uses descriptive anchor text to link to the SEO audit page where they can be reviewed.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "internal-linking",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Перелинковка",
    enTerm: "Internal linking",
    ruDefinition: "Система внутренних ссылок, которая соединяет связанные страницы сайта.",
    enDefinition: "A system of internal links connecting related pages across a website.",
    ruPlain: "Страницы не остаются изолированными: читатель и поисковый робот могут перейти к логичному продолжению.",
    enPlain: "Pages are not left isolated: readers and crawlers can move to the logical next page.",
    ruWhy: "Перелинковка помогает обнаруживать страницы, передаёт контекст и ведёт посетителя к следующему действию.",
    enWhy: "Internal linking helps discovery, supplies context and guides visitors towards the next action.",
    ruExample: "Статья о бесплатной проверке ведёт на услугу аудита, а страница услуги — на подтверждающий кейс.",
    enExample: "An article about a free check links to the audit service, and the service links to an evidence-based case.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "duplicate-page",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Дубль страницы",
    enTerm: "Duplicate page",
    ruDefinition: "Отдельный URL с полностью или почти полностью совпадающим содержанием другой страницы.",
    enDefinition: "A separate URL whose content fully or substantially matches another page.",
    ruPlain: "Сайт показывает один и тот же ответ по нескольким адресам, хотя самостоятельной пользы у каждой копии нет.",
    enPlain: "The website serves the same answer at several addresses even though each copy provides no independent value.",
    ruWhy: "Дубли расходуют обход, усложняют выбор основной версии и могут разделять ссылки и другие сигналы между URL.",
    enWhy: "Duplicates consume crawl activity, complicate primary-page selection and can split links and other signals across URLs.",
    ruExample: "Категория с пустым параметром сортировки повторяет чистую категорию и должна быть объединена редиректом или canonical.",
    enExample: "A category with an empty sort parameter repeats the clean category and should be consolidated with a redirect or canonical.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "schema-org",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Schema.org",
    enTerm: "Schema.org",
    ruDefinition: "Общий словарь типов и свойств для машиночитаемого описания сущностей веб-страницы.",
    enDefinition: "A shared vocabulary of types and properties for machine-readable descriptions of web-page entities.",
    ruPlain: "Он задаёт согласованные названия для объектов вроде организации, статьи, товара, цены или автора и связей между ними.",
    enPlain: "It provides agreed names for entities such as organisations, articles, products, prices or authors and the relationships between them.",
    ruWhy: "Единый словарь уменьшает неоднозначность: разные системы могут одинаково интерпретировать факты, переданные страницей.",
    enWhy: "A common vocabulary reduces ambiguity because different systems can interpret the page facts in the same way.",
    ruExample: "Статья использует тип Article и свойства headline, datePublished и author из словаря Schema.org.",
    enExample: "An article uses the Article type and the headline, datePublished and author properties from Schema.org.",
    relatedHref: "/web-development",
  },
  {
    slug: "structured-data",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Структурированные данные",
    enTerm: "Structured data",
    ruDefinition: "Машиночитаемая разметка, которая явно описывает сущности и свойства страницы.",
    enDefinition: "Machine-readable markup that explicitly describes page entities and their properties.",
    ruPlain: "Это понятная поисковой системе карточка фактов: что перед ней — статья, товар, организация или другой объект.",
    enPlain: "It is a fact card for search engines that states whether the page represents an article, product, organisation or another entity.",
    ruWhy: "Корректная разметка уменьшает неоднозначность и даёт поиску данные для расширенного представления результата.",
    enWhy: "Correct markup reduces ambiguity and gives search engines data for richer result presentation.",
    ruExample: "Карточка товара передаёт название, цену, наличие и бренд через Product-разметку.",
    enExample: "A product page supplies its name, price, availability and brand through Product markup.",
    relatedHref: "/web-development",
  },
  {
    slug: "json-ld",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "JSON-LD",
    enTerm: "JSON-LD",
    ruDefinition: "Формат передачи связанных структурированных данных отдельным JSON-блоком в HTML-документе.",
    enDefinition: "A format for supplying linked structured data in a separate JSON block within an HTML document.",
    ruPlain: "Факты о странице записывают в одном техническом блоке, не смешивая их с видимой HTML-разметкой каждого элемента.",
    enPlain: "Page facts are recorded in one technical block rather than mixed into the visible HTML markup of each element.",
    ruWhy: "Формат удобен для поддержки сложных сущностей и связей, но данные в нём должны совпадать с видимым содержанием.",
    enWhy: "The format is convenient for maintaining complex entities and relationships, but its data must match visible page content.",
    ruExample: "JSON-LD статьи связывает заголовок, дату публикации, автора, изображение и канонический адрес в объекте Article.",
    enExample: "Article JSON-LD connects the headline, publication date, author, image and canonical address in one Article object.",
    relatedHref: "/web-development",
  },
  {
    slug: "core-web-vitals",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Core Web Vitals",
    enTerm: "Core Web Vitals",
    ruDefinition: "Набор полевых метрик Google для оценки загрузки, отзывчивости и визуальной стабильности страницы.",
    enDefinition: "A set of Google field metrics for page loading, responsiveness and visual stability.",
    ruPlain: "Показатели LCP, INP и CLS описывают опыт реальных посетителей на разных устройствах и соединениях.",
    enPlain: "LCP, INP and CLS describe the experience of real visitors across different devices and connections.",
    ruWhy: "Полевые данные показывают проблемы, которые лабораторный тест одного быстрого компьютера может не воспроизвести.",
    enWhy: "Field data reveals problems that a laboratory test on one fast computer may fail to reproduce.",
    ruExample: "Отчёт сравнивает 75-й процентиль LCP, INP и CLS за период, а не делает вывод по одному запуску Lighthouse.",
    enExample: "A report compares the 75th percentile of LCP, INP and CLS over time instead of relying on one Lighthouse run.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "lcp",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "LCP",
    enTerm: "LCP",
    ruDefinition: "Метрика времени до отрисовки крупнейшего видимого элемента содержимого в области просмотра.",
    enDefinition: "A metric measuring the time until the largest visible content element renders in the viewport.",
    ruPlain: "Она отвечает, когда основной крупный текст, баннер или изображение стало видно посетителю после открытия страницы.",
    enPlain: "It indicates when the main large text block, banner or image becomes visible after the visitor opens the page.",
    ruWhy: "Медленный LCP означает, что ключевой смысл долго остаётся скрытым из-за сервера, изображения, шрифтов или блокирующих ресурсов.",
    enWhy: "A slow LCP means the main content remains hidden because of server time, images, fonts or render-blocking resources.",
    ruExample: "Главное изображение сжимают, заранее задают размер и загружают без ленивой задержки, чтобы сократить LCP.",
    enExample: "The hero image is compressed, dimensioned and loaded without lazy delay to improve LCP.",
    relatedHref: "/web-development",
  },
  {
    slug: "cls",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "CLS",
    enTerm: "CLS",
    ruDefinition: "Метрика суммарной величины неожиданных сдвигов видимых элементов во время жизни страницы.",
    enDefinition: "A metric for the cumulative amount of unexpected movement among visible elements during a page visit.",
    ruPlain: "CLS растёт, когда уже показанный текст или кнопка внезапно смещается из-за поздно появившегося изображения, рекламы или шрифта.",
    enPlain: "CLS increases when visible text or a button suddenly moves because an image, advert or font appears late.",
    ruWhy: "Сдвиги мешают чтению и могут заставить человека нажать не на тот элемент, поэтому место динамического контента резервируют заранее.",
    enWhy: "Layout shifts interrupt reading and can cause accidental clicks, so space for dynamic content should be reserved in advance.",
    ruExample: "Для фотографии задают ширину и высоту, поэтому браузер оставляет место ещё до загрузки файла.",
    enExample: "An image has explicit width and height, allowing the browser to reserve space before the file loads.",
    relatedHref: "/web-development",
  },
  {
    slug: "tbt",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "TBT",
    enTerm: "TBT",
    ruDefinition: "Лабораторный показатель времени, когда главный поток заблокирован длинными задачами.",
    enDefinition: "A lab metric measuring how long the main thread is blocked by long tasks.",
    ruPlain: "Показывает, сколько времени страница занята тяжёлой работой и не может быстро ответить на действие пользователя.",
    enPlain: "It shows how long the page is busy with heavy work and cannot respond promptly to user input.",
    ruWhy: "Высокий TBT помогает найти JavaScript и другие задачи, из-за которых интерфейс ощущается зависшим.",
    enWhy: "A high TBT helps identify JavaScript and other work that makes the interface feel frozen.",
    ruExample: "Большой скрипт блокирует нажатие на меню на 600 мс после загрузки.",
    enExample: "A large script blocks the menu interaction for 600 ms after loading.",
    relatedHref: "/web-development",
  },
  {
    slug: "inp",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "INP",
    enTerm: "INP",
    ruDefinition: "Полевая метрика задержки между действиями пользователя и следующей визуальной реакцией страницы.",
    enDefinition: "A field metric for the delay between user interactions and the page's next visual response.",
    ruPlain: "Она оценивает, насколько быстро интерфейс отвечает на клики, касания и ввод на протяжении реального посещения.",
    enPlain: "It evaluates how quickly the interface responds to clicks, taps and keyboard input throughout a real visit.",
    ruWhy: "Высокий INP указывает на тяжёлые обработчики или длинные задачи, из-за которых рабочая кнопка ощущается зависшей.",
    enWhy: "A high INP points to heavy handlers or long tasks that make a functional control feel frozen.",
    ruExample: "Код фильтра разбивают на короткие задачи, чтобы выбранный параметр отображался сразу даже на слабом телефоне.",
    enExample: "Filter work is split into shorter tasks so the selected option appears promptly even on a slower phone.",
    relatedHref: "/web-development",
  },
  {
    slug: "ctr",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "CTR",
    enTerm: "CTR",
    ruDefinition: "Доля кликов среди всех показов поискового результата, объявления или другого элемента.",
    enDefinition: "The share of clicks among all impressions of a search result, advert or other element.",
    ruPlain: "Показатель рассчитывают как число кликов, делённое на число показов, и выражают в процентах.",
    enPlain: "The metric is calculated by dividing clicks by impressions and expressing the result as a percentage.",
    ruWhy: "CTR помогает сравнивать привлекательность показов, но без позиции, аудитории и конверсии не доказывает качество трафика.",
    enWhy: "CTR helps compare impression appeal, but without position, audience and conversion it does not prove traffic quality.",
    ruExample: "У объявления 1000 показов и 40 кликов: CTR равен 4%, после чего отдельно оценивают стоимость и заявки.",
    enExample: "An advert has 1,000 impressions and 40 clicks, giving a 4% CTR; cost and enquiries are then evaluated separately.",
    relatedHref: "/yandex-ads",
  },
  {
    slug: "conversion",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Конверсия",
    enTerm: "Conversion",
    ruDefinition: "Целевое действие пользователя и доля посетителей, которые его совершили.",
    enDefinition: "A target user action and the share of visitors who complete it.",
    ruPlain: "Это нужный бизнесу результат визита: заявка, звонок, покупка или другое заранее выбранное действие.",
    enPlain: "It is the visit outcome the business needs, such as an enquiry, call, purchase or another agreed action.",
    ruWhy: "Без конкретной конверсии нельзя связать изменения сайта или рекламы с измеримым результатом.",
    enWhy: "Without a defined conversion, website or advertising changes cannot be tied to a measurable outcome.",
    ruExample: "Из 200 посетителей форму отправили 8: конверсия формы составила 4%.",
    enExample: "Eight of 200 visitors submit the form, giving the form a 4% conversion rate.",
    relatedHref: "/yandex-ads",
  },
  {
    slug: "search-semantics",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Семантика",
    enTerm: "Search semantics",
    ruDefinition: "Совокупность поисковых формулировок, тем и пользовательских намерений, относящихся к сайту или разделу.",
    enDefinition: "The collection of search phrases, topics and user intents relevant to a website or section.",
    ruPlain: "Это язык реального спроса: какие задачи люди вводят в поиск, какими словами и какого ответа ожидают.",
    enPlain: "It is the language of actual demand: the tasks people enter into search, the words they use and the answer they expect.",
    ruWhy: "Анализ семантики помогает создавать страницы под разные задачи, а не механически повторять популярные ключевые фразы.",
    enWhy: "Semantic analysis helps create pages for distinct needs instead of mechanically repeating popular keywords.",
    ruExample: "Запросы о цене аудита, самостоятельной проверке и исправлении ошибок разделяют по разным намерениям и форматам ответа.",
    enExample: "Queries about audit pricing, self-checking and error remediation are separated by intent and answer format.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "query-cluster",
    indexable: true,
    updatedAt: "2026-08-28",
    ruTerm: "Кластер запросов",
    enTerm: "Query cluster",
    ruDefinition: "Группа поисковых запросов с настолько близким намерением и составом результатов, что на них может отвечать одна целевая страница.",
    enDefinition: "A group of search queries whose intent and result sets are close enough to be answered by one target page.",
    ruPlain: "Разные формулировки объединяют, если пользователь ожидает один и тот же тип ответа; отдельную страницу под каждую похожую ключевую фразу не создают.",
    enPlain: "Different phrases are grouped when users expect the same type of answer; a separate page is not created for every similar keyword variation.",
    ruWhy: "Кластеризация превращает семантику в понятную структуру сайта, уменьшает дубли и каннибализацию и показывает, какой URL продвигать по группе спроса.",
    enWhy: "Clustering turns search demand into a clear site structure, reduces duplication and cannibalisation, and identifies the URL to promote for each demand group.",
    ruExample: "Запросы «заказать SEO-аудит» и «цена SEO-аудита» могут вести на одну коммерческую страницу, а «как провести SEO-аудит» — на отдельное руководство.",
    enExample: "Queries such as “book an SEO audit” and “SEO audit price” may share one commercial page, while “how to run an SEO audit” belongs in a separate guide.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "semantic-core",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Семантическое ядро",
    enTerm: "Keyword set",
    ruDefinition: "Проверенный набор поисковых запросов, сгруппированных по темам и намерениям.",
    enDefinition: "A validated set of search queries grouped by topic and intent.",
    ruPlain: "Это карта того, как люди формулируют свои задачи в поиске и каким страницам отвечать на каждую формулировку.",
    enPlain: "It is a map of how people phrase their needs in search and which page should answer each query group.",
    ruWhy: "Ядро помогает планировать структуру без случайных страниц и бессмысленного повторения фраз.",
    enWhy: "The set helps plan a deliberate structure without random pages or mechanical phrase repetition.",
    ruExample: "Запросы про цену аудита относятся к коммерческой странице, а запросы про состав аудита — к объясняющему материалу.",
    enExample: "Audit-price queries belong on a commercial page, while audit-scope queries can be answered by an explanatory article.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "query-clustering",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Кластеризация",
    enTerm: "Query clustering",
    ruDefinition: "Объединение поисковых запросов в группы, которые может полноценно закрыть одна страница.",
    enDefinition: "Grouping search queries that can be answered well by a single page.",
    ruPlain: "Похожие по задаче формулировки собирают вместе, а разные намерения разводят по отдельным страницам.",
    enPlain: "Phrases with the same job are kept together, while different intents are assigned to different pages.",
    ruWhy: "Кластеризация предотвращает лишние страницы и помогает не смешивать разные пользовательские задачи.",
    enWhy: "Clustering prevents unnecessary pages and avoids mixing different user needs on one page.",
    ruExample: "Запросы «заказать SEO-аудит» и «стоимость SEO-аудита» могут вести на одну страницу услуги.",
    enExample: "Queries such as “order an SEO audit” and “SEO audit cost” can lead to one service page.",
    relatedHref: "/seo-promotion",
  },
  {
    slug: "search-intent",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Поисковый интент",
    enTerm: "Search intent",
    ruDefinition: "Задача, которую пользователь хочет решить своим поисковым запросом.",
    enDefinition: "The task a user wants to complete with a search query.",
    ruPlain: "Важно не только какие слова введены, но и нужен ли человеку ответ, сравнение, адрес или покупка.",
    enPlain: "The words alone are not enough: the user may need an answer, comparison, location or purchase.",
    ruWhy: "Страница, не соответствующая намерению, редко помогает посетителю даже при точном совпадении ключевой фразы.",
    enWhy: "A page that misses the intent rarely helps the visitor even when it contains the exact query wording.",
    ruExample: "По запросу «что входит в SEO-аудит» человеку нужен состав работ, а не форма заказа без объяснения.",
    enExample: "For “what does an SEO audit include”, the user needs a scope explanation rather than an unexplained order form.",
    relatedHref: "/content-materials",
  },
  {
    slug: "page-cannibalisation",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Каннибализация страниц",
    enTerm: "Page cannibalisation",
    ruDefinition: "Ситуация, когда несколько страниц одного сайта конкурируют за одну поисковую задачу.",
    enDefinition: "A situation where several pages on one website compete for the same search task.",
    ruPlain: "Поиску трудно выбрать главный ответ, потому что сайт предлагает несколько почти одинаковых страниц.",
    enPlain: "Search engines struggle to choose the primary answer because the website offers several nearly identical pages.",
    ruWhy: "Конкурирующие страницы могут менять позиции друг друга и размывать накопленные сигналы.",
    enWhy: "Competing pages can displace one another and split the signals each page has accumulated.",
    ruExample: "Две страницы «SEO-аудит сайта» различаются только переставленными абзацами и претендуют на один запрос.",
    enExample: "Two “website SEO audit” pages differ only by reordered paragraphs and target the same query.",
    relatedHref: "/seo-audit",
  },
  {
    slug: "landing-page",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Посадочная страница",
    enTerm: "Landing page",
    ruDefinition: "Страница, собранная вокруг одной аудитории, задачи или конкретного предложения и следующего действия.",
    enDefinition: "A page organised around one audience, task or specific offer and its next action.",
    ruPlain: "Она последовательно отвечает на один сценарий посетителя: объясняет предложение, снимает ключевые вопросы и ведёт к понятному шагу.",
    enPlain: "It follows one visitor scenario by explaining the offer, answering key questions and leading to a clear next step.",
    ruWhy: "Сфокусированная страница согласует ожидание из поиска или рекламы с содержанием и не заставляет искать нужную услугу по всему сайту.",
    enWhy: "A focused page aligns search or advertising expectations with content and avoids making visitors hunt across the website.",
    ruExample: "Посадочная SEO-аудита показывает проблему, состав проверки, результат, цену и кнопку перехода к брифу.",
    enExample: "An SEO audit landing page presents the problem, review scope, deliverable, price and a link to the brief.",
    relatedHref: "/web-development",
  },
  {
    slug: "product-feed",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Товарный фид",
    enTerm: "Product feed",
    ruDefinition: "Структурированный файл или поток данных с товарами, ценами, остатками, ссылками и характеристиками.",
    enDefinition: "A structured file or data stream containing products, prices, stock, links and attributes.",
    ruPlain: "Магазин регулярно передаёт площадке единообразный каталог, чтобы та могла обновлять предложения без ручного заполнения каждой карточки.",
    enPlain: "A shop regularly supplies a standardised catalogue so the platform can update offers without manually editing every card.",
    ruWhy: "Ошибки идентификаторов, обязательных полей или форматов приводят к отклонению товаров, неверным ценам и устаревшим остаткам.",
    enWhy: "Identifier, required-field or format errors can cause rejected products, incorrect prices and stale stock information.",
    ruExample: "Фид для Яндекс Маркета передаёт SKU, название, URL, изображение, цену, наличие и значения обязательных характеристик.",
    enExample: "A Yandex Market feed supplies the SKU, name, URL, image, price, availability and required attribute values.",
    relatedHref: "/marketplaces/yandex-market",
  },
  {
    slug: "product-attribute",
    indexable: true,
    updatedAt: "2026-08-28",
    ruTerm: "Атрибут товара",
    enTerm: "Product attribute",
    ruDefinition: "Нормализованная характеристика товара, которую каталог и маркетплейс используют в карточке, фильтрах, сравнении и товарном фиде.",
    enDefinition: "A normalised product characteristic used by catalogues and marketplaces in cards, filters, comparisons and product feeds.",
    ruPlain: "Это структурированная пара «поле — значение», например «материал — хлопок», а не свободное рекламное описание товара.",
    enPlain: "It is a structured field-and-value pair, such as “material — cotton”, rather than unrestricted promotional product copy.",
    ruWhy: "Полные и единообразные атрибуты помогают площадке правильно отнести товар к категории, показать его в фильтрах и не отклонить предложение из-за обязательного поля.",
    enWhy: "Complete, consistent attributes help a platform classify the product, include it in filters and avoid rejecting the offer because a required field is missing.",
    ruExample: "Для футболки передают бренд, материал, цвет и размер; цвет описывает модель, а размер отличает конкретные варианты SKU.",
    enExample: "A T-shirt supplies brand, material, colour and size; colour describes the model, while size distinguishes individual SKU variants.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "sku",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "SKU",
    enTerm: "SKU",
    ruDefinition: "Уникальная товарная позиция, обычно отличающаяся конкретным набором характеристик.",
    enDefinition: "A unique stock-keeping unit, usually defined by a specific combination of product attributes.",
    ruPlain: "Это отдельный вариант товара, который магазин учитывает и продаёт как самостоятельную позицию.",
    enPlain: "It is a distinct product variant that the seller tracks and sells as its own item.",
    ruWhy: "Корректное разделение SKU влияет на остатки, цены, варианты и качество данных в карточке.",
    enWhy: "Correct SKU separation affects stock, pricing, variants and product-card data quality.",
    ruExample: "Одна модель футболки в размерах S и M — два разных SKU.",
    enExample: "The same T-shirt model in sizes S and M represents two separate SKUs.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "product-card",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Карточка товара",
    enTerm: "Product card",
    ruDefinition: "Страница товара с названием, характеристиками, изображениями, ценой и условиями покупки.",
    enDefinition: "A product page containing the name, attributes, images, price and purchase conditions.",
    ruPlain: "Это основная страница, на которой покупатель понимает товар и принимает решение о покупке.",
    enPlain: "It is the main page where a shopper understands the product and decides whether to buy it.",
    ruWhy: "Полнота и согласованность карточки влияют на поиск по каталогу, доверие и конверсию.",
    enWhy: "A complete, consistent product card affects catalogue discovery, trust and conversion.",
    ruExample: "Карточка обуви показывает модель, размерную сетку, материал, фото, цену и наличие.",
    enExample: "A footwear card shows the model, size guide, material, images, price and availability.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "rich-content",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "Rich Content",
    enTerm: "Rich Content",
    ruDefinition: "Расширенный визуальный контент карточки товара: дополнительные блоки, изображения и объяснения.",
    enDefinition: "Enhanced visual content for a product card, including extra blocks, images and explanations.",
    ruPlain: "Это подробная презентация товара ниже основных характеристик, если площадка поддерживает такой формат.",
    enPlain: "It is a more detailed product presentation below the core attributes when the marketplace supports the format.",
    ruWhy: "Rich Content может наглядно объяснить сложный товар, но не заменяет точные основные характеристики.",
    enWhy: "Rich Content can explain a complex product visually, but it does not replace accurate core attributes.",
    ruExample: "Для кофемашины добавляют схему режимов, размеры и последовательность ухода.",
    enExample: "A coffee-machine card adds a mode diagram, dimensions and a maintenance sequence.",
    relatedHref: "/marketplaces",
  },
  {
    slug: "ab-testing",
    indexable: true,
    updatedAt: "2026-08-24",
    ruTerm: "A/B-тестирование",
    enTerm: "A/B testing",
    ruDefinition: "Сравнение двух вариантов при контролируемом распределении аудитории.",
    enDefinition: "A comparison of two variants using a controlled audience split.",
    ruPlain: "Часть людей видит вариант A, часть — вариант B, после чего результат сравнивают по заранее выбранной метрике.",
    enPlain: "Some users see variant A and others see variant B, then results are compared using a metric chosen in advance.",
    ruWhy: "Тест помогает отличить реальный эффект изменения от случайных колебаний и субъективного мнения.",
    enWhy: "The test helps separate a real effect from random variation and subjective preference.",
    ruExample: "Сравнивают две формулировки кнопки по доле отправленных форм при одинаковых условиях.",
    enExample: "Two button labels are compared by form-completion rate under the same conditions.",
    relatedHref: "/content-materials",
  },
  {
    slug: "acceptance-criterion",
    indexable: true,
    updatedAt: "2026-08-28",
    ruTerm: "Критерий приёмки",
    enTerm: "Acceptance criterion",
    ruDefinition: "Заранее согласованное измеримое условие, по которому результат работы однозначно принимают или отправляют на доработку.",
    enDefinition: "A measurable condition agreed in advance that determines whether completed work passes or must be revised.",
    ruPlain: "До начала изменения фиксируют наблюдаемый результат и способ проверки, чтобы слово «готово» не зависело от субъективной оценки исполнителя.",
    enPlain: "Before a change begins, the expected observable result and verification method are recorded so that “done” does not depend on the implementer’s opinion.",
    ruWhy: "Критерий связывает задачу с тестом, позволяет автоматике остановить неудачную публикацию и даёт человеку понятное доказательство успешного исправления.",
    enWhy: "The criterion links a task to a test, lets automation stop a failed release and gives a reviewer clear evidence that the fix succeeded.",
    ruExample: "После правки десять выбранных URL возвращают 200, не содержат noindex, указывают canonical на себя и проходят повторный crawl без прежней ошибки.",
    enExample: "After the fix, ten selected URLs return 200, contain no noindex directive, use self-referencing canonicals and pass a repeat crawl without the original issue.",
    relatedHref: "/brief",
  },
];

export const glossaryTerms: GlossaryTerm[] = sources.map((source) => ({
  slug: source.slug,
  indexable: source.indexable === true,
  updatedAt: source.updatedAt ?? "2026-08-24",
  ru: {
    term: source.ruTerm,
    definition: source.ruDefinition,
    plain: source.ruPlain ?? `Проще: ${source.ruDefinition.charAt(0).toLowerCase()}${source.ruDefinition.slice(1)}`,
    why: source.ruWhy ?? "Термин помогает точно описать проблему, договориться о результате и проверить работу.",
    example: source.ruExample,
    relatedLabel: "Связанный раздел",
    relatedHref: source.relatedHref,
  },
  en: {
    term: source.enTerm,
    definition: source.enDefinition,
    plain: source.enPlain ?? `In plain language: ${source.enDefinition.charAt(0).toLowerCase()}${source.enDefinition.slice(1)}`,
    why: source.enWhy ?? "The term helps define the issue, agree the outcome and verify delivery.",
    example: source.enExample,
    relatedLabel: "Related page",
    relatedHref: `/en${source.relatedHref}`,
  },
}));

export const indexableGlossarySlugs = glossaryTerms
  .filter((term) => term.indexable)
  .map((term) => term.slug);

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find((term) => term.slug === slug);
}

export function getRelatedGlossaryTerms(slug: string, limit = 3): GlossaryTerm[] {
  const current = getGlossaryTerm(slug);
  if (!current) return [];
  return glossaryTerms
    .filter((term) => term.slug !== slug && term.ru.relatedHref === current.ru.relatedHref)
    .slice(0, Math.max(0, limit));
}
