"use client";

import { useMemo, useState } from "react";
import type { Locale } from "../../config/site";
import { calculateEstimate, type CalculatorAnswers, type CalculatorKind } from "../../config/calculator";
import { formatPrice } from "../../config/prices";
import { collectBrowserAttribution } from "../../lib/attribution";
import { useCsrf } from "./useCsrf";
import { TurnstileField } from "./TurnstileField";
import { ConsentNotice } from "./ConsentNotice";

const kinds: Array<{ id: CalculatorKind; ru: string; en: string }> = [
  { id: "audit", ru: "SEO-аудит", en: "SEO audit" }, { id: "seo", ru: "Продвижение", en: "SEO growth" },
  { id: "marketplaces", ru: "Маркетплейсы", en: "Marketplaces" }, { id: "development", ru: "Разработка", en: "Development" },
];

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="calculator-field"><span>{label}</span>{children}</label>; }

export function Calculator({ locale, enPricing }: { locale: Locale; enPricing?: { currency: string; rate: number } }) {
  const ru = locale === "ru"; const { token, refresh } = useCsrf();
  const [kind, setKind] = useState<CalculatorKind>("audit"); const [answers, setAnswers] = useState<CalculatorAnswers>({ pages: 50, scale: "base", items: 1, package: "audit", siteType: "landing", languages: 1, regions: 1 });
  const [submitted, setSubmitted] = useState(""); const [turnstileToken, setTurnstileToken] = useState<string>(); const [turnstileReset, setTurnstileReset] = useState(0); const estimate = useMemo(() => calculateEstimate(kind, answers, locale), [answers, kind, locale]);
  const update = (key: string, value: string | number | boolean) => setAnswers((current) => ({ ...current, [key]: value }));
  const money = (value: number) => formatPrice(value, locale, { perMonth: kind === "seo", english: enPricing });
  const estimateLabel = (() => { const min = money(estimate.min); const max = money(estimate.max); return min === max ? min : `${min}–${max}`; })();
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSubmitted(ru ? "Отправляем…" : "Sending…"); const form = new FormData(event.currentTarget); const csrf = token || await refresh();
    const attribution = collectBrowserAttribution();
    const response = await fetch("/api/calculator", { method: "POST", headers: { "content-type": "application/json", "x-csrf-token": csrf }, body: JSON.stringify({ name: form.get("name"), contact: form.get("contact"), consent: form.get("consent") === "on", honeypot: form.get("company"), turnstileToken, locale, kind, answers, estimate, source: "calculator", ...attribution }) });
    setSubmitted(response.ok ? (ru ? "Расчёт сохранён. Свяжемся в рабочее время и уточним объём." : "Estimate saved. We will follow up during working hours.") : (ru ? "Не удалось отправить. Проверьте контакт." : "Could not submit. Check the contact field."));
    if (!response.ok) setTurnstileReset((value) => value + 1);
  }
  return <div className="calculator"><div className="calculator-tabs" role="tablist" aria-label={ru ? "Тип расчёта" : "Estimate type"}>{kinds.map((item) => <button role="tab" aria-selected={kind === item.id} key={item.id} onClick={() => setKind(item.id)}>{ru ? item.ru : item.en}</button>)}</div>
    <div className="calculator-body"><div className="calculator-fields">
      {kind === "audit" && <><Field label={ru ? "Предполагаемое число страниц" : "Approximate page count"}><input type="number" min="1" max="100000" value={Number(answers.pages)} onChange={(e) => update("pages", Number(e.target.value))}/></Field><Field label={ru ? "Сложность сайта" : "Website complexity"}><select value={String(answers.complex ?? "normal")} onChange={(e) => update("complex", e.target.value)}><option value="normal">{ru ? "Обычный сайт" : "Standard"}</option><option value="high">{ru ? "Каталог, фильтры, интеграции" : "Catalogue, filters, integrations"}</option></select></Field><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.implementation)} onChange={(e) => update("implementation", e.target.checked)}/><span>{ru ? "Нужно внедрение исправлений" : "Implementation required"}</span></label><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.urgent)} onChange={(e) => update("urgent", e.target.checked)}/><span>{ru ? "Срочная работа" : "Urgent delivery"}</span></label></>}
      {kind === "seo" && <><Field label={ru ? "Масштаб работы" : "Scope"}><select value={String(answers.scale)} onChange={(e) => update("scale", e.target.value)}><option value="base">{ru ? "База" : "Foundation"}</option><option value="growth">{ru ? "Рост" : "Growth"}</option><option value="full">{ru ? "Полное сопровождение" : "Full partnership"}</option></select></Field><Field label={ru ? "Число регионов" : "Number of regions"}><input type="number" min="1" max="20" value={Number(answers.regions)} onChange={(e) => update("regions", Number(e.target.value))}/></Field><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.technical)} onChange={(e) => update("technical", e.target.checked)}/><span>{ru ? "Нужны технические работы" : "Technical work required"}</span></label><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.ads)} onChange={(e) => update("ads", e.target.checked)}/><span>{ru ? "Нужно ведение Яндекс Рекламы" : "Yandex Ads management"}</span></label></>}
      {kind === "marketplaces" && <><Field label={ru ? "Площадка" : "Platform"}><select onChange={(e) => update("platform", e.target.value)}><option>Wildberries</option><option>Ozon</option></select></Field><Field label={ru ? "Число артикулов" : "Number of SKUs"}><input type="number" min="1" max="500" value={Number(answers.items)} onChange={(e) => update("items", Number(e.target.value))}/></Field><Field label={ru ? "Пакет" : "Package"}><select value={String(answers.package)} onChange={(e) => update("package", e.target.value)}><option value="audit">{ru ? "Аудит" : "Audit"}</option><option value="optimization">SEO</option><option value="turnkey">{ru ? "Под ключ" : "Turnkey"}</option></select></Field><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.video)} onChange={(e) => update("video", e.target.checked)}/><span>{ru ? "Нужно видео" : "Video required"}</span></label><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.analytics)} onChange={(e) => update("analytics", e.target.checked)}/><span>{ru ? "Регулярная аналитика" : "Recurring analytics"}</span></label></>}
      {kind === "development" && <><Field label={ru ? "Тип сайта" : "Website type"}><select value={String(answers.siteType)} onChange={(e) => update("siteType", e.target.value)}><option value="landing">{ru ? "Лендинг" : "Landing page"}</option><option value="corporate">{ru ? "Корпоративный" : "Corporate"}</option><option value="commerce">{ru ? "Каталог или магазин" : "Catalogue or commerce"}</option></select></Field><Field label={ru ? "Языковые версии" : "Languages"}><input type="number" min="1" max="10" value={Number(answers.languages)} onChange={(e) => update("languages", Number(e.target.value))}/></Field><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.account)} onChange={(e) => update("account", e.target.checked)}/><span>{ru ? "Личный кабинет" : "User account"}</span></label><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.integrations)} onChange={(e) => update("integrations", e.target.checked)}/><span>{ru ? "Сложные интеграции" : "Complex integrations"}</span></label><label className="toggle-field"><input type="checkbox" checked={Boolean(answers.urgent)} onChange={(e) => update("urgent", e.target.checked)}/><span>{ru ? "Сжатый срок" : "Compressed timeline"}</span></label></>}
    </div><aside className="estimate-panel"><p className="eyebrow">{ru ? "Предварительная стоимость" : "Preliminary estimate"}</p><h2>{estimateLabel}</h2><p>{ru ? "Это не оферта и не окончательная смета." : "This is not a binding quote."}</p><ul>{estimate.factors.map((factor) => <li key={factor}>{factor}</li>)}</ul><form method="post" onSubmit={submit}><input name="name" aria-label={ru ? "Имя" : "Name"} placeholder={ru ? "Имя" : "Name"} required/><input name="contact" aria-label={ru ? "Telegram или e-mail" : "Telegram or email"} placeholder={ru ? "Telegram или e-mail" : "Telegram or email"} required/><input className="honeypot" name="company" aria-label="Company" tabIndex={-1}/><label className="check-field"><input name="consent" type="checkbox" required/><ConsentNotice locale={locale}/></label><TurnstileField onToken={setTurnstileToken} resetKey={turnstileReset}/>{submitted && <p role="status">{submitted}</p>}<button className="button button-primary" disabled={!token || !turnstileToken}>{ru ? "Отправить расчёт" : "Send estimate"}<span>↗</span></button></form></aside></div></div>;
}
